language: ruby
rvm:
  - 2.4.0
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:create --all
  - bundle exec rails db:migrate
script:
  - bundle exec rails ci:tests
services:
  - postgresql
notifications:
  email: false
branches:
  only:
    - master
addons:
  sauce_connect: true
